version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: Jhunior_Critina
      MYSQL_USER: userUpds
      MYSQL_PASSWORD: updsPassword
    volumes:
      - mysql-data:/var/lib/mysql 
      - ./proyectoFinal.sql:/docker-entrypoint-initdb.d/proyectoFinal.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: userUpds
      MYSQL_PASSWORD: updsPassword
      MYSQL_ROOT_PASSWORD: rootPassword

volumes:
  mysql-data: